name: Testes Regressivos

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 17 * * 1-5'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Instalar o chromedriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb

      - uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional          

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci

      - name: Gerar relatório na falha
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-execution
          path: "**/formated-report/"

      - name: Enviar Notificação slack - Sucesso
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: devops-resultado-testes
            SLACK_COLOR: ${{ job.status }}
            SLACK_MESSAGEM: 'Teste executado com sucesso" :white_check_mark:'
            SLACK_TITLE: 'Teste executado com sucesso" :white_check_mark:'
            SLACK_USERNAME: SUCESSO

      - name: Enviar Notificação slack - Erro
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: devops-resultado-testes
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGEM: 'Erro ao executar teste" :fire:'
          SLACK_TITLE: 'Erro ao executar teste" :fire:'
          SLACK_USERNAME: FALHA